services:
  web:
    image: dsstore.devforge.uz:5000/delivery/dev/test-proj:55f9c41f
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:alpine
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
